# Generated by Django 3.2 on 2021-04-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tip',
            field=models.CharField(max_length=140),
        ),
    ]
