# Generated by Django 3.2 on 2021-06-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_alter_tweet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
